---
title: "Explore Correlations"
author: "Anik Mallick"
date: "01/09/2019"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Explore Correlations

In this app you can explore correlation of a dataset. It is possible to upload you own data to check correlation or just try the app out with datasets in R base system. The Home page of the app will give information to get you started. [Go to the app](https://anik-mallick.shinyapps.io/ExploreCorrelations/)


My github repo for the [project](https://github.com/AnikMallick/Explore_Correlations_With_R_Shiny)

## Load data

In this tab, clicking on 'Load' will load the data into the app, you can update the names of the columns but for that you have to mention all the column names in proper order, you can use the datatable shown beside to take help. After giving new colnames clicking on 'Update' will update the data. At any point clicking on the 'Reset' will reset the data to its primery state. You can also convert any column to numeric, factor or charecter. If you are loading your own data you need to select the 'upload data' selection from the 'Dataset' dropdown. Verious tabs here show verious stats of the data.
             
## CorrelationsFunnel

In this tab, select colums you want to drop (not mendatory). Then cliking on 'Make Binary' will convert all the columns to binary data, then select the terget and click on 'Generate plot' to generate the plot. With the range selector it is possible to select the range of the plot. For more info please visit: https://business-science.github.io/correlationfunnel/index.html

## Correlogram

In this tab, select colums you want to drop (not mendatory). Then select all the paremeters for the corrplot. Correlation method, Handle Na values, Order, Method, Sig test and Conf interval.For more info on this: https://cran.r-project.org/web/packages/corrplot/vignettes/corrplot-intro.html
